/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MeuPrimeiroProjeto;

public class App {

    public static void main(String[] args) {
        System.out.println("Olá mundo");
        System.out.println("Meu segundo comendao de sáida!");
    }
}
