/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MeuPrimeiroProjeto;

public class App {

    public static void main(String[] args) {
        System.out.println("Olá mundo");
        System.out.println("Meu segundo comendo de sáida!");
        System.out.println("Meu terceiro comando");
        System.out.println("meu quarto comando!");
    }
}
